### ISSUE TITLE
Licenze

### ISSUE THREAD

**Issue by alemulaz** [CIGNo-project/CIGNo#17]
Creare licenza dell'atlante della laguna e sostituirla nel portale al posto di quella del CNR-ISMAR nella home page.
Per i dati dell'atlante avremo la tipologial iodl 2.0 (vedi punto 8) oppure le lincenze definite dal proprietario/i del dato: potremmo scivere come nei metadatini che ci sono ora in pmapper: "Definita dal proprietario del dato" perchè altrimenti dovremmo stare dietro alle licenze dei vari proprietari dei dati

**Comment by menegon** [comment]
Ora è disponibile, nella parte di admin, un gestore di licenze. L'amministratore definire una lista di licenza, specificando per ciascuna di essere nome / abstract / url. L'utente, in fase di compilazione può accedere a questa lista
