### ISSUE TITLE
Non si possono scorrere tutti i termini

### ISSUE THREAD

**Issue by alemulaz** [CIGNo-project/CIGNo#18]
METADATI: in Editing, per il campo Topic category non si riescono a scorrere tutti i termini disponibili

![Immagine](https://f.cloud.github.com/assets/3063682/21583/bfd57a4a-49be-11e2-9fce-4e08b4b24aab.GIF)

**Comment by menegon** [comment]
Aggiunto atuoScroll in Ext.ux.form.MultiSelect
